#access to remote mysql base
[database]
host = '144.0.0.0'
login = 'YOURLOGIN'
passwd = 'YOURPASS'
port = '3306'
name = 'DB_NAME'

[dbtable]
updtable = 'table_for_update'
updrow = 'row'
updwhere = '3'
updwhere2 = "21"

[web]
page = 'https://example.com/prices/'
page_upd = 'https://example.com/prices/'
replacestr = ["text1","'ukrsymbol","'ukrsymbol2 (for example '—è)", "etc"]
add_string_before = '<h6>SOME TEXT</h6>'